# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c82297175f85a30f227958b7deb0f0866a4759452a5717817eea370a37651999191eb90c314634937173463293e34bc7e35e5a007be599595bc3455fbf6fa1d

test:
  secret_key_base: 7570486dafe6406c3ef2d729360a1f43aec8868ffac3ccb9c0245b9458672552c3ee9ece95bddba5f1e22a748b0a9649abbfa64a531ce080a49461d074e9cf61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
